name: Push to Forked Repository

on:
  push:
    branches:
      - sam-patch

jobs:
  push_to_forked_repo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Push to Forked Repository
      run: |
        git config --global user.email "samshervin.sebastian@gmail.com"
        git config --global user.name "sam-shervin"
        git checkout sam-patch
        git pull
        git config pull.rebase false
        git remote add hackhub-24-testdeploy https://github.com/sam-shervin/hackhub-24-testdeploy
        git pull hackhub-24-testdeploy master --allow-unrelated-histories
        git push hackhub-24-testdeploy sam-patch:master --force
