name: Push to Forked Repository

on:
  push:
    branches:
      - sam-patch

jobs:
  push_to_forked_repo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Pull changes from origin (upstream)
      run: git pull origin sam-patch

    - name: Fetch latest changes from remote (hackhub-24-testdeploy)
      run: git fetch origin

    - name: Push to Forked Repository
      run: |
        git remote add hackhub-24-testdeploy https://github.com/sam-shervin/hackhub-24-testdeploy
        git push hackhub-24-testdeploy sam-patch:master
