name: Push to Forked Repository

on:
  push:
    branches:
      - sam-patch

jobs:
  push_to_forked_repo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Push to Forked Repository
      run: |
        git checkout sam-patch
        git config pull.rebase false
        git remote add hackhub-24-testdeploy https://github.com/sam-shervin/hackhub-24-testdeploy
        git pull hackhub-24-testdeploy master
        git push hackhub-24-testdeploy sam-patch:master
