name: Create Pull Request

on:
  push:
    branches:
      - master

jobs:
  create_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Automated pull request'
          title: 'Automated pull request'
          body: |
            This pull request is automatically created whenever changes are pushed to the `master` branch
          branch: master
          base: master
          branch-suffix: pr-${{ github.run_number }}
          # Change the below repository names accordingly
          repository: sam-shervin/hackhub-24-testdeploy
