name: Push to Forked Repository

on:
  push:
    branches:
      - sam-patch  # You can specify the branch you want to trigger this workflow for

jobs:
  push_to_forked_repo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2  # This action checks out your repository

    # If needed, set up any environment variables or configurations here

    - name: Push to Forked Repository
      run: |
        git pull
        git remote add hackhub-24-testdeploy https://github.com/sam-shervin/hackhub-24-testdeploy
        git push hackhub-24-testdeploy sam-patch:master
