name: Push to Fork

on:
  push:
    branches:
      - sam-patch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Push to Fork
      uses: ad-m/push-to-fork@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch_to_push: sam-patch
        fork_branch: sam-shervin/hackhub-24-testdeploy/master
